### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by qiangqiangqiang123** [jiazheng-xing/SloshNet#1]
Hello!Could you mind sharing your datasets that have been extracted into frames?

**Comment by jiazheng-xing** [comment]
Our dataset download is sourced from https://box.nju.edu.cn/d/dc97163752fc4024be2c/.

**Comment by qiangqiangqiang123** [comment]
Thank you for your sharing！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月16日(星期一) 下午5:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jiazheng-xing/SloshNet] Dataset (Issue #1)





 
Our dataset download is sourced from https://box.nju.edu.cn/d/dc97163752fc4024be2c/.

**Comment by WL13143** [comment]
您好，想问一下run.py中args.path ='/public/datasets_neo/hmdb51/extracted_frames'，这一部分是保存的数据预处理的结果嘛？不知道extracted_frames在哪里获取，谢谢您！！
